packages:
  - codex-cli
  - docs
  - packages/*
  - youtube-recs-prototype
  - youtube-recs-web

ignoredBuiltDependencies:
  - esbuild

patchedDependencies:
  marked-terminal@7.3.0: patches/marked-terminal@7.3.0.patch
